package com.assembleia.controledevotos.exception;

public class AssociadoNotFoundException extends Throwable {

    public AssociadoNotFoundException() {
        super("Associado n√£o encontrado.");
    }
}
